Set status non required
MapColonies/job-manager pull request #25
Opened 2023-05-24 12:44 UTC by ronnahom96

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2023-05-28 07:05 UTC, netanelC approved these changes
Good Job!

2023-05-28 08:11 UTC, asafMasa requested changes
Please fix the lint errors

2023-05-28 14:22 UTC, ronnahom96 commented
> Please fix the lint errors

done

2023-05-29 10:36 UTC, asafMasa approved these changes

2023-05-29 10:55 UTC, RonitKissis approved these changes

2023-05-29 10:56 UTC, merged