fix: removed chart name from template names
MapColonies/job-manager pull request #30
Opened 2023-09-07 10:30 UTC by nitzanmorr

to eliminate duplicates

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2023-09-07 13:08 UTC, asafMasa requested changes

2023-09-07 13:08 UTC, asafMasa commented on helm/templates/deployment.yaml
> +        - name: {{ $releaseName }}-deployment
check

2023-09-07 13:42 UTC, asafMasa approved these changes

2023-09-10 08:18 UTC, CL-SHLOMIKONCHA approved these changes

2023-09-10 08:34 UTC, netanelC approved these changes

2023-09-10 08:41 UTC, merged