Release-tasks-of-aborted-job
MapColonies/job-manager pull request #31
Opened 2023-10-20 08:46 UTC by netanelC

When changing the status of inactive task, we need to change it according to job status.
This PR fixes it

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✔                                                                       |

2024-02-07 10:05 UTC, asafMasa requested changes
Looks good, thanks!

2024-02-07 10:05 UTC, asafMasa commented on src/DAL/repositories/taskRepository.ts
> +      const res = await this.createQueryBuilder()
why do you run on each task a different query?
can't you run this update in single query with an array of task id's? or at lease 2 queries for each status?

2024-02-07 10:05 UTC, asafMasa commented on src/DAL/repositories/taskRepository.ts
> +    const getJobStatusQuery = `
shouldn't this method be executed inside a transacion context? to prevent status update while processing this method?

2024-02-07 17:22 UTC, netanelC commented on src/DAL/repositories/taskRepository.ts
> +    const getJobStatusQuery = `
You need the Job Repo in the query and you are in the EntityRepository of TaskEntity. I couldn't find a convenient solution for including 2 entities in a transaction.

2024-02-07 18:34 UTC, netanelC commented on src/DAL/repositories/taskRepository.ts
> +      const res = await this.createQueryBuilder()
You are right! Refactored :)

2024-02-08 07:44 UTC, asafMasa approved these changes

2024-02-12 08:46 UTC, merged