Adding traces support(MAPCO-3893)
MapColonies/job-manager pull request #36
Opened 2024-02-22 13:56 UTC by almog8k

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

Further  information:
Adding traces support.

2024-02-25 08:28 UTC, alebinson approved these changes
Looks good (decoration principles are nice and clear)

2024-02-25 09:53 UTC, asafMasa requested changes

2024-02-25 09:53 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "url": "TELEMETRY_TRACING_URL",
add to default config

2024-02-25 09:53 UTC, asafMasa commented on src/jobs/models/jobManager.ts
> +  @withSpanAsyncV4
add for getAvailableActions, isAbortable

2024-02-25 09:53 UTC, asafMasa commented on src/taskManagement/models/taskManagementManger.ts
> +  @withSpanAsyncV4
remove

2024-02-25 13:53 UTC, asafMasa approved these changes

2024-02-26 12:58 UTC, alebinson approved these changes
looks good

2024-02-26 14:03 UTC, netanelC approved these changes

2024-02-26 14:13 UTC, merged