fix: handle ingestion vs export raster jobs with nullish identifier
MapColonies/job-manager pull request #39
Opened 2024-07-02 13:00 UTC by ronenkapelian

Ingestion: the constraint include resourceId, version type only
Export: the constraint include also the "additionalIdentifiers" column as part of constraint

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2024-07-04 13:39 UTC, asafMasa requested changes

2024-07-04 13:39 UTC, asafMasa commented on src/DAL/migration/v.2.6.2.sql
> +	WHERE ("additionalIdentifiers" IS NULL)
check for status not as in constraint

2024-07-08 07:28 UTC, ronenkapelian commented on src/DAL/migration/v.2.6.2.sql
> +	WHERE ("additionalIdentifiers" IS NULL)
done

2024-07-08 08:50 UTC, asafMasa approved these changes

2024-07-08 10:32 UTC, netanelC approved these changes

2024-07-08 10:38 UTC, RonitKissis approved these changes
g8!

2024-07-08 10:41 UTC, merged