fix: log of inactive tasks(MAPCO-5876)
MapColonies/job-manager pull request #49
Opened 2024-12-16 14:04 UTC by RonitKissis

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2024-12-16 14:18 UTC, CL-SHLOMIKONCHA approved these changes

2024-12-16 14:24 UTC, CL-SHLOMIKONCHA requested changes

2024-12-16 14:24 UTC, CL-SHLOMIKONCHA commented on src/taskManagement/models/taskManagementManger.ts
> +      `finding tasks inactive for longer then ${req.inactiveTimeSec} seconds, with types:  ${
then -> than

2024-12-16 14:31 UTC, netanelC approved these changes

2024-12-16 14:31 UTC, netanelC requested changes
This is not a "fix" commit

2024-12-16 15:21 UTC, asafMasa approved these changes

2024-12-17 14:09 UTC, CL-SHLOMIKONCHA approved these changes

2024-12-17 14:14 UTC, netanelC approved these changes

2024-12-17 14:16 UTC, merged